#!/bin/bash

# Enkouyami's Bash Minecraft Installer
# Copyright © 2012-2013  Ely Lizaire

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# For any suggestions or feedback, reach me at http://www.minecraftforum.net/topic/1114574-bash-minecraft-installer/ or send me an e-mail at enkouyami@gmail.com

# This script was inspired by Alloc's Minecraft Installer at http://www.minecraftforum.net/topic/250945-install-ubuntu-minecraft-installer-update-20/
# Alloc's e-mail: Alloc@dr.com

# This script attempts to install Minecraft, Oracle Java, Sun Java, and or OpenJDK.
# It can also troubleshoot common problems that may arise.
#------------------------------------------------------

tput clear # clear the screen by scrolling down enough
# Setting color 
txtred=$(tput setaf 1) # Red
txtgrn=$(tput setaf 2) # Green
txtylw=$(tput setaf 3) # Yellow
txtblu=$(tput setaf 4) # Blue
txtpur=$(tput setaf 5) # Purple
txtcyn=$(tput setaf 6) # Cyan
txtbld=$(tput bold) # Bold mode
txtrst=$(tput sgr0) # Text reset.

echo "------------------------------------------------------"
echo "$txtbld${txtylw}Enkouyami's Bash Minecraft Installer  Copyright (C) 2012  Ely Lizaire"
echo "This program comes with ABSOLUTELY NO WARRANTY; for details type 'show w'."
echo "This is free software, and you are welcome to redistribute it"
echo "under certain conditions; type 'show c' for details."
echo ""
echo "${txtgrn} _____________________________________________"
echo "/*  ***    **       *****       **      ***  *\ "
echo "|*********************************************| "
echo "|*    Enkouyami's Bash Minecraft Installer   *|"
echo "|*                Version 1.4                *|" 
echo "|*               26 March 2012               *|"
echo "|*      My email: enkouyami@gmail.com        *|"
echo "|*********************************************|"
echo "\_____________________________________________/$txtrst"
echo "Visit$txtcyn http://www.minecraftforum.net/topic/1114574-bash-minecraft-installer/$txtrst or e-mail$txtcyn enkouyami@gmail.com$txtrst for more help."

#------------------#
#   License Menu   #
#------------------#
licenseMenu() {
echo ""
echo "${txtylw}The GPLv3 license imposes the requirement that any freedom that is granted regarding the original work must be granted on exactly the same or compatible terms in any derived work."$txtrst
echo ""
echo "1) to download the full license details at$txtcyn http://www.gnu.org/licenses/gpl-3.0.txt$txtrst and then press 'q' to quit reading"
echo "2) to go back to main menu."
echo ""
read input -p "${txtbld}Enter your choice [1-2]$txtrst"
case $input in
	1 ) Showlicense
	return;;
	2 | q ) return
	return;;
	*) echo "${txtred}Invalid choice!$txtrst"
	return
esac
} ## END LicenseMenu

#----------------#
#  Show License  #
#----------------#
Showlicense() {
License='$(dirname -- "$0")/gpl-3.0.txt' # GNU General Public license
cd '$(dirname -- "$0")' && wget -c http://www.gnu.org/licenses/gpl-3.0.txt
less "$License" # Can either use the basic "more", or "less", dialog, and "most" to display the file.
} ## END ShowLicense

counter=1
#-----------#
#   Dots    #
#-----------#
# This simply prints three Dots. It waits .1 seconds between each dot.
Dots() {
while [ $counter -le 3 ]
do
echo -n "."
sleep .1
((counter++))
done
let counter=1
echo ""
} ## END Dots

#-------------------#
#   Java Checking   #
#-------------------#
CheckJavas() { # Here, this script will attempt to check for Java by checking to see if installation folders are present.
echo "Checking for Java"
Dots
echo ""
echo "Looking for Sun Java 6"
if [ -e /usr/lib/jvm/java-6-sun ] && [ -e /usr/lib/jvm/java-6-sun/bin ] && [ -e /usr/lib/jvm/java-6-sun/bin/java ]
then
	echo "${txtgrn}Sun Java 6 is installed!$txtrst"
	echo ""
else
	echo "${txtred}Sun Java 6 is NOT installed$txtrst"
	echo ""
fi
echo -n "Looking for Oracle Java 7"
Dots
if [ -e /usr/lib/jvm/java-7-oracle ] && [ -e /usr/lib/jvm/java-7-oracle/bin ] && [ -e /usr/lib/jvm/java-7-oracle/bin/java ]
then
	echo "${txtcyn}Oracle Java 7 is installed"
	echo ""
else
	echo "${txtred}Oracle Java 7 is NOT installed$txtrst"
	echo ""
fi
echo -n "Looking for OpenJDK 6"
Dots
if [ -e /usr/lib/jvm/java-6-openjdk-common ] && [ -e /usr/lib/jvm/java-6-openjdk-common/jre ] && [ -e /usr/lib/jvm/java-6-openjdk-common/jre/lib ]
then
	echo "${txtgrn}OpenJDK 6 is installed$txtrst"
	echo ""
else
	echo "${txtred}OpenJDK 7 is NOT installed$txtrst"
	echo ""
fi
echo -n "Looking for OpenJDK 7"
Dots
if [ -e /usr/lib/jvm/java-7-openjdk-common ] && [ -e /usr/lib/jvm/java-7-openjdk-common/jre ] && [ -e /usr/lib/jvm/java-7-openjdk-common/jre/lib ]
then
	echo "${txtgrn}OpenJDK 7 is installed$txtrst"
	echo ""
else
	echo "${txtred}OpenJDK 7 is NOT installed$txtrst"
	echo ""
fi
echo "${txtylw}Detected java folders:$txtrst"
ls /usr/lib/jvm/
echo ""
echo "${txtylw}Default java client detected:$txtrst"
java -version
} ## END CheckJavas

#-----------------#
#    Java Menu    #
#-----------------#
JavaMenu() {
echo "------------------------------------------------------"; echo ""
echo "#---------------------#"
echo "#      Java Menu      #"
echo "#---------------------#"
echo "What would you like to do?"; echo ""
echo "${txtgrn}1) Check the default Java client"
echo "2) Install Oracle/Sun Java (Recommended)"
echo "3) Install OpenJDK"
echo "4) Manually select which Java to use (Recommended)"
echo "5) Use OpenJDK 7 to run minecraft from now on"
echo "6) Use Oracle Java 7 to run minecraft from now on"
echo "7) Use Sun Java 6 to run minecraft from now on(May not work)"
echo "8) Go back to main menu$txtrst"
echo ""
read input -p "${txtbld}Enter your choice [1-8]$txtrst"
case $input in
	1 ) java -version
	JavaMenu;;
	2 ) OracleJavaMenu
	JavaMenu;;
	3 ) OpenJDKInstall
	javac -version;;
	4 ) sudo update-alternatives --config java
	sudo update-alternatives --config javac
	sudo update-alternatives --config javaws
	echo ""; echo "${txtgrn}Done!$txtrst"; echo "";
	JavaMenu;;
	5 ) OpenJDKDefault
	JavaMenu;;
	6 ) OracleJavaDefaultA
	JavaMenu;;
	7 ) SunJavaDefault
	JavaMenu;;
	8 | q | 255) return;;
	* ) echo "${txtred}Invalid choice!$txtrst"
	JavaMenu
esac
} ## END JavaMenu

#----------------------#
#   Oracle Java Menu   #
#----------------------#
OracleJavaMenu() {
echo "------------------------------------------------------"
echo ""
echo "${txtbld}$txtgrn#-------------------------------------#"
echo "#   Oracle/Sun Java Menu   #"
echo "#-------------------------------------#$txtrst"	
echo "${txtgrn}Install Oracle Java 7"
echo "2. Install/update Sun Java 6"
echo ""
read input
case $input in
	1 ) OracleJavaInstallA;;
	2 ) SunJavaInstallA;;
	* ) echo ""; echo "${txtred}Invalid choice!$txtrst"
esac
} ## END OracleJavaMenu

#--------------------------------#
#   Oracle Java 7 InstallationA  #
#--------------------------------#
OracleJavaInstallA() {
echo "Do you wish to purge OpenJDK from your system? [${txtred}y$txtrst/${txtred}N$txtrst]"
echo ""
read input
case $input in
	y | Y ) PurgeOpenJDK
	OracleJavaInstallB;;
	n | N ) OracleJavaInstallB;;
	* ) echo "" ${txtred}echo "Invalid choice!$txtrst"
esac
} ## END OracleJavaInstallA

#-----------------------#
#    Purge OpenJDK 7    #
#-----------------------#
PurgeOpenJDK() {
echo -n "${txtred}Purging OpenJDK from your system!$txtrst"
Dots
echo "${txtylw}That requires root access"
sudo apt-get purge openjdk* && sudo apt-get purge icedtea6*
echo "" echo "${txtgrn}Done!$txtrst"; echo ""
} ## END PurgeOpenJDK

#---------------------------------#
#   Oracle Java 7 InstallationB   #
#---------------------------------#
OracleJavaInstallB() {
echo "Do you wish to add the PPA? [${txtred}y$txtrst/${txtred}N$txtrst]"
echo ""
read input
case $input in
	y | Y ) OracleJava7PPA
	OracleJavaInstall;;
	n | N ) OracleJavaInstall;;
	* ) echo "" echo "${txtred}Invalid choice!$txtrst"
esac
} ## END OracleJavaInstallB

#-----------------------------#
#  Install Oracle Java 7 ppa  #
#-----------------------------#
OracleJava7PPA() {
echo -n "${txtgrn}Adding Oracle Java 7 PPA"
Dots
echo "${txtylw}That requires root access$"
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
echo ""; echo "${txtgrn}Done!$txtrst"; echo ""
} ## END OracleJava7PPA

#-------------------------#
#  Oracle Java 7 Install  #
#-------------------------#
OracleJavaInstall() {
echo -n "${txtgrn}Installing Oracle Java 7"
Dots	
echo "${txtylw}That requires root access"
sudo mkdir -p /usr/lib/mozilla/plugins
sudo apt-get install Oraclejava7-installer
echo ""; echo "${txtgrn}Done!$txtrst"; echo ""
} ## END OracleJavaInstall

#--------------------------------#
#  Set Oracle Java 7 as Default  #
#--------------------------------#
OracleJavaDefaultA() {
echo -n "${txtgrn}Making Oracle Java the default$txtrst"
Dots
echo "Don't worry if you see lots of errors"
sudo update-java-alternatives -s java-7-oracle
echo ""; echo "${txtgrn}Done!$txtrst"; echo ""
} ## END OracleJavaDefaultA

#-------------------#
#  OpenJDK Install  #
#-------------------#
OpenJDKInstall() {
echo -n "${txtgrn}Starting OpenJDK installation"
Dots
echo "${txtylw}That requires root access"
sudo mkdir -p /usr/lib/mozilla/plugins
sudo apt-get install openjdk-7-jre icedtea-7-plugin
echo ""; echo "${txtgrn}Done!$txtrst"; echo ""
} ## END OpenJDKInstall

#--------------------------#
#  Set OpenJDK as Default  #
#--------------------------#
OpenJDKDefault() {
echo -n "${txtgrn}Making OpenJDK the default$txtrst"
Dots
echo "Don't worry if you see lots of errors"
sudo update-java-alternatives -s java-1.7.0-openjdk-i386
echo ""; echo "${txtgrn}Done!$txtrst"; echo ""
} ## END OpenJDKDefault

#----------------------#
#  Install Sun Java 6  #
#----------------------#
SunJavaInstallA() {
	echo ""
	echo -n "${txtgrn}Installing Sun Java 6$txtrst"
	Dots
	echo "Do you wish to add the PPA? [${txtgrn}y${txtrst}/${txtred}N${txtrst}]"
	echo ""
	read input
	case $input in
		y | Y ) SunJavaInstallPPA
		SunJavaInstall
		return;;
		n | N ) SunJavaInstall
		return;;
		* ) echo "${txtred}Invalid choice!$txtrst"
		InstallJavaA
	esac
} ## END SunJavaInstallA

#----------------------#
#  Install Sun Java 6  #
#----------------------#
SunJavaInstall() {
echo "${txtgrn}Installing Sun Java 6"
echo "${txtylw}That requires root access"
sudo mkdir -p /usr/lib/mozilla/plugins
sudo apt-get install update-sun-jre
echo ""; echo "${txtgrn}Done!$txtrst"; echo ""
} ## END SunJavaInstall

#--------------------------#
#  Install Sun Java 6 PPA  #
#--------------------------#
SunJavaInstallPPA() {
echo "${txtylw}That requires root access$txtrst"
sudo add-apt-repository 'deb http://www.duinsoft.nl/pkg debs all/'
sudo apt-get update
} ## END SunJavaInstallPPA

#-----------------------------#
#  Set Sun Java 6 as Default  #
#-----------------------------#
SunJavaDefault() {
echo -n "${txtgrn}Making Sun Java the default$txtrst"
Dots
echo "Don't worry if you see lots of errors"
echo ""
sudo update-java-alternatives -s java-6-sun
sudo update-java-alternatives -s java-6-sun-i386
echo ""; echo "${txtgrn}Done!$txtrst"; echo ""
} ## END SunJavaDefault

#---------------------#
#  Install Minecraft  #
#---------------------#
InstallMinecraft() { # Here this script will first check to see if the user already has minecraft.jar
# If so, it won't be downloaded.
echo ""
echo "$txtbld${txtgrn}#--------------------------#"
echo "#  Minecraft Installation  #"
echo "#--------------------------#"
echo ""
echo -n "Checking if minecraft is already installed"
Dots
echo ""
if [ -e /home/$(whoami)/.minecraft/install_files ]
then
	echo  -ne "${txtred}Removing unnecessary install_files folder$txtrst"
	rm -rf /home/$(whoami)/.minecraft/install_files
fi
if [ -e /home/$(whoami)/.minecraft/minecraft.jar ]
then
	echo  "${txtgrn}Minecraft is already present!"
	return
else
	cd /home/$(whoami)
	if [ ! -e /home/$(whoami)/.minecraft ]
	then
		echo -n "${txtgrn}Creating ~/.minecraft"
		Dots
		echo ""
		mkdir .minecraft
	fi
fi
cd /home/$(whoami)/.minecraft
echo -n "${txtgrn}Downloading minecraft.jar"
Dots
wget -q www.minecraft.net/download/minecraft.jar
echo -n "${txtgrn}Downloading the icon to ~/.minecraft"
Dots
wget -q http://www.minecraft.net/favicon.png
mv /home/$(whoami)/.minecraft/favicon.png /home/$(whoami)/.minecraft/Minecraft.png
echo ""
echo "${txtgrn}Minecraft has finished downloading!"
echo ""
#--------------------------------------------
echo -n "${txtgrn}Setting up the minecraft /usr/local/games shell script"
Dots
# This writes a shell script in the /usr/local/games folder, if it already exists in /usr/local/games or /usr/local/bin, it will be replaced.
if [ -e /usr/local/games/minecraft ]
then
	echo -n "${txtred}Removing previous version"
	Dots
	echo ""
	rm -rf /usr/local/games/minecraft
fi
if [ -e /usr/local/bin/minecraft ]
then
	echo -n "Removing previous version"
	Dots
	rm -rf /usr/local/bin/minecraft
fi
touch minecraft
echo "java -jar /home/$(whoami)/.minecraft/minecraft.jar" >> minecraft
echo ""
echo -n "${txtgrn}Moving and changing permission of Minecraft shell script"
Dots
echo "${txtylw}That requires root access"
sudo chmod +x minecraft
sudo mv minecraft /usr/local/games/
echo "${txtgrn}Done!"
echo ""
#--------------------------------------------
echo "$Installing the minecraft icon"
xdg-desktop-icon install --novendor /home/$(whoami)/.minecraft/Minecraft.png
rm -rf Minecraft.png
echo ""
#--------------------------------------------
echo -n "Creating a desktop launcher"
Dots
if [ -e /home/$(whoami)/Minecraft.desktop ]
then
	rm -rf /home/$(whoami)/Minecraft.desktop
fi
touch 'Minecraft.desktop'
echo "[Desktop Entry]" >> Minecraft.desktop
echo "Version=1.0" >> Minecraft.desktop
echo "Name=Minecraft" >> Minecraft.desktop
echo "GenericName=Game" >> Minecraft.desktop
echo "Comment=Minecraft is a game about placing blocks to build anything you can imagine." >> Minecraft.desktop
echo "Exec=minecraft" >> Minecraft.desktop
echo "Terminal=false" >> Minecraft.desktop
echo "Icon=Minecraft"  >> Minecraft.desktop
echo "Categories=Game;Application;" >> Minecraft.desktop
echo "Type=Application" >> Minecraft.desktop
echo "StartupNotify=true" >> Minecraft.desktop
echo "Actions=RunInTerminal" >> Minecraft.desktop
echo "" >> Minecraft.desktop
echo "[Desktop Action RunInTerminal]" >> Minecraft.desktop
echo "Name=Run in Terminal" >> Minecraft.desktop
echo "Exec=sudo gnome-terminal -x minecraft" >> Minecraft.desktop
#---------------------------------------------
echo -n "$Granting the launcher executable permissions and adding it to your desktop$"
Dots
echo "${txtylw}That requires root access"
sudo chmod +x Minecraft.desktop
cp Minecraft.desktop /home/$(whoami)/Desktop
echo "${txtgrn}Done!"; echo ""
#----------------------------------------------------
echo -n "$Adding it to your application menu$"
Dots
xdg-desktop-menu install --novendor Minecraft.desktop
xdg-desktop-menu forceupdate
rm -rf Minecraft.desktop
rm -rf /home/$(whoami)/Desktop/Minecraft.png
echo ""
#---------------------------------------------
# This writes a script that will add /usr/local/games to PATH which will then allow the user to run minecraft from terminal, just by typing "minecraft"
if [ ! -e /home/$(whoami)/.minecraft/add_usr-local-games_to_PATH.sh ]
then
	rm -rf add_usr-local-games_to_PATH.sh
fi
if [ ! -e /etc/profile.d/add_usr-local-games_to_PATH.sh ]
then
	echo -n "${txtgrn}Adding /usr/local/games to PATH so you can run minecraft with 'minecraft' from terminal$txtrst"
	Dots
	touch add_usr-local-games_to_PATH.sh
	echo "# set PATH so it includes /usr/local/games if it exists" >> add_usr-local-games_to_PATH.sh
	echo "if [ -e '/usr/local/games' ]
then" >> add_usr-local-games_to_PATH.sh
echo "	export PATH=/usr/local/games:$PATH" >> add_usr-local-games_to_PATH.sh
echo "fi" >> add_usr-local-games_to_PATH.sh
sudo chmod +x add_usr-local-games_to_PATH.sh
sudo mv add_usr-local-games_to_PATH.sh /etc/profile.d/add_usr-local-games_to_PATH.sh
source /etc/profile.d/add_usr-local-games_to_PATH.sh
echo ""
fi
#---------------------------------------------
echo "Success!$txtrst"
echo ""
echo -n "Hopefully Minecraft has been successfully downloaded and installed without any problems. Check your desktop and Applications menu for launchers. You can also run it from terminal with a 'minecraft' command."
echo "Visit the forum at ${txtcyn}http://www.minecraftforum.net/topic/1114574-bash-minecraft-installer/$txtrst or e-mail me at ${txtcyn}enkouyami@gmail.com$txtrst if you have any questions"
echo "Enjoy! :D"
echo ""
} ## END InstallMinecraft

#-----------------------#
#  Uninstall Minecraft  #
#-----------------------#
UninstallMinecraft() {
echo -n "Looking for Minecraft"
Dots
if [ -e /home/$(whoami)/.minecraft/minecraft.jar ]
then
	echo "${txtgrn}Minecraft found!"
	echo -n "Uninstalling$txtrst"
	cd /home/$(whoami)/.minecraft
	Dots
	echo ""
	echo "Do you wish to save your settings and save data? [${txtgrn}y${txtrst}/${txtred}N$txtrst]"
	read input
	case $input in
		y | Y ) UninstallMinecraftA
		echo "";;
		n | N ) UninstallMinecraftB
		echo "";;
		* ) echo "${txtred}Invalid choice!$txtrst";;
	esac
UninstallMinecraft2
else
	echo "${txtred}Minecraft not detected!$txtrst"
fi
} ## END UninstallMinecraft

#------------------------#
#  Uninstall MinecraftA  #
#------------------------#
UninstallMinecraftA() {
	echo -n "${txtgrn}Uninstalling minecraft while keeping your personal data"
	Dots
	echo ""
if [ -e /home/$(whoami)/.minecraft/install_files ]
then
	echo  -ne "${txtred}Removing install_files folder$txtrst"
	echo ""
	rm -rf /home/$(whoami)/.minecraft/install_files
fi
	rm -rf bin
	rm -rf texturepacks
	rm minecraft.jar
	rm -rf minecraft
	rm -rf resources
} ## END UninstallMinecraftA

#------------------------#
#  Uninstall MinecraftB  #
#------------------------#
UninstallMinecraftB() {
	echo -n "${txtred}Removing minecraft folder"
	Dots
	echo ""
	rm -rf /home/$(whoami)/.minecraft
	echo ""
} ## END UninstallMinecraftB

#------------------------#
#  Uninstall Minecraft2  #
#------------------------#
UninstallMinecraft2() {
echo "Uninstalling the icon"
xdg-desktop-icon uninstall --novendor Minecraft.png
echo ""
#--------------------------------------------
echo ""
echo -n "${txtred}Removing menu launcher"
Dots
xdg-desktop-menu uninstall Minecraft.desktop
echo ""
#--------------------------------------------
if [ -e /home/$(whoami)/Desktop/Minecraft.desktop ]
then
	echo -n "Removing Desktop launcher"
	Dots
	rm -rf /home/$(whoami)/Desktop/Minecraft.desktop
	echo ""
fi
#--------------------------------------------
echo -n "Removing Launcher in '/usr/local/games'"
Dots
echo "${txtylw}That requires root access"
sudo rm -rf /usr/local/games/minecraft
echo ""
if [ -e /usr/local/games/minecraft ]
then
	echo -n "${txtred}Removing launcher in '/usr/local/bin/minecraft'"
	rm -rf /usr/local/bin/minecraft
	fi
	echo "${txtylw}Minecraft has been uninstalled :($txtrst"
} ## END UninstallMinecraft2

#----------------------------#
#  Install Minecraft Server  #
#----------------------------#
ServerInstall() {
echo ""
echo "$txtbld${txtgrn}#----------------------------------#"
echo "#  Minecraft Server Installation   #"
echo "#----------------------------------#$txtrst"
echo ""
echo -n "${txtylw}Checking if minecraft server is already installed"
Dots
if [ -e /home/$(whoami)/Minecraft_Server/bin/minecraft_server.jar ]
then
	echo "Minecraft server client is already present!"
	return
else
echo ""
echo -n "${txtgrn}Installing Minecraft Server"
Dots
echo ""
fi
if [ ! -e /home/$(whoami)/Minecraft_Server ]
then
	echo -n "Creating ~/Minecraft_Server"
	Dots
	mkdir /home/$(whoami)/Minecraft_Server
fi
cd /home/$(whoami)/Minecraft_Server
if [ ! -e /home/$(whoami)/Minecraft_Server/bin ]
then
	echo -n "Creating ~/Minecraft_Server/bin"
	Dots
	echo ""
	mkdir bin
fi
cd bin
echo -n "Downloading minecraft_server.jar"
Dots
wget -q http://www.minecraft.net/download/minecraft_server.jar
echo -n "Downloading the icon to ~/Minecraft_Server"
Dots
wget -q http://i.imgur.com/ugDRM.png
mv /home/$(whoami)/Minecraft_Server/bin/ugDRM.png /home/$(whoami)/Minecraft_Server/bin/Minecraft_Server.png
echo ""
echo "Minecraft Server has finished downloading!"
echo ""
#---------------------------------------------
echo -n "Setting up the Minecraft '/usr/local/games' shell script"
Dots
# This writes a shell script in the /usr/local/games folder, if it already exists in /usr/local/games or /usr/local/bin, it will be replaced.
if [ -e /usr/local/games/minecraft_server ]
then
	echo -n "${txtred}Removing previous version"
	Dots
	rm -rf /usr/local/games/minecraft_server
fi
if [ -e /usr/local/bin/minecraft_server ]
then
	echo -n "Removing previous version"
	Dots
	rm -rf /usr/local/bin/minecraft_server
fi
touch minecraft_server
echo "java -Xmx1024M -Xms1024M -jar /home/$(whoami)/Minecraft_Server/bin/minecraft_server.jar" >> minecraft_server
echo -n "${txtgrn}Moving and changing permission of Minecraft shell script"
Dots
echo "${txtylw}That requires root access"
sudo chmod +x minecraft_server
sudo mv minecraft_server /usr/local/games
echo "${txtgrn}Done!"
echo ""
#--------------------------------------------
echo "${txtgrn}Installing the minecraft icon"
xdg-desktop-icon install --novendor /home/$(whoami)/.minecraft/Minecraft_Server.png
rm -rf Minecraft_Server.png
echo ""
#---------------------------------------------
echo -n "Creating a desktop launcher"
Dots
if [ -e /home/$(whoami)/Minecraft_Server.desktop ]
then
	rm -rf /home/$(whoami)/Minecraft_Server.desktop
fi
touch Minecraft_Server.desktop
echo "[Desktop Entry]" >> Minecraft_Server.desktop
echo "Version=1.0" >> Minecraft_Server.desktop
echo "Name=Minecraft Server" >> Minecraft_Server.desktop
echo "GenericName=Server game client GUI" >> Minecraft_Server.desktop
echo "Comment=Minecraft Server GUI" >> Minecraft_Server.desktop
echo "Exec=minecraft" >> Minecraft_Server.desktop
echo "Terminal=false" >> Minecraft_Server.desktop
echo "Icon=Minecraft_Server"  >> Minecraft_Server.desktop
echo "Categories=Game;Application;" >> Minecraft_Server.desktop
echo "Type=Application" >> Minecraft_Server.desktop
echo "StartupNotify=true" >> Minecraft_Server.desktop
echo "Actions=RunInTerminal" >> Minecraft_Server.desktop
echo "" >> Minecraft_Server.desktop
echo "[Desktop Action RunInTerminal]" >> Minecraft_Server.desktop
echo "Name=Run in Terminal" >> Minecraft_Server.desktop
echo "Exec=sudo gnome-terminal -x minecraft" >> Minecraft_Server.desktop
#----------------------------------------------------
echo -n "Granting the launcher executable permissions and adding it to your desktop"
Dots
echo "${txtylw}That requires root access"
sudo chmod +x Minecraft_Server.desktop
cp Minecraft_Server.desktop /home/$(whoami)/Desktop
echo "${txtgrn}Done!"
echo ""
#---------------------------------------------
echo -n "Adding it to your application menu"
Dots
xdg-desktop-menu install --novendor Minecraft_Server.desktop
xdg-desktop-menu forceupdate
rm -rf Minecraft_Server.desktop
rm -rf /home/$(whoami)/Desktop/Minecraft_Server.png
echo "Done!"
echo ""
#---------------------------------------------
# This writes a script that will add /usr/local/games to PATH which will then allow the user to run Minecraft Server from terminal, just by typing "minecraft_server"
if [ ! -e /home/$(whoami)/.minecraft/add_usr-local-games_to_PATH.sh ]
then
	rm -rf add_usr-local-games_to_PATH.sh
fi
if [ ! -e /etc/profile.d/add_usr-local-games_to_PATH.sh ]
then
	echo "Adding /usr/local/games to PATH so you can run minecraft with 'minecraft' from terminal"
	Dots
	touch add_usr-local-games_to_PATH.sh
	echo "# set PATH so it includes /usr/local/games if it exists" >> add_usr-local-games_to_PATH.sh
	echo "if [ -e '/usr/local/games' ]
then" >> add_usr-local-games_to_PATH.sh
echo "	export PATH=/usr/local/games:$PATH" >> add_usr-local-games_to_PATH.sh
echo "fi" >> add_usr-local-games_to_PATH.sh
sudo chmod +x add_usr-local-games_to_PATH.sh
sudo mv add_usr-local-games_to_PATH.sh /etc/profile.d/add_usr-local-games_to_PATH.sh
source /etc/profile.d/add_usr-local-games_to_PATH.sh
echo "Done!"
echo ""
fi
#---------------------------------------------
echo "Success!"
echo ""
echo -n "${txtylw}Hopefully Minecraft Server has been successfully downloaded and installed without any problems. Check your desktop and Applications menu for launchers. You can also run it from terminal with a 'minecraft' command."
echo "Visit the forum at ${txtcyn}http://www.minecraftforum.net/topic/1114574-bash-minecraft-installer/$txtylw or e-mail me at$txtcyn enkouyami@gmail.com${txtylw} if you have any questions"
echo "${txtgrn}Enjoy! :D$txtrst"
echo ""
} ## END ServerInstall

#------------------------------#
#  Uninstall Minecraft Server  #
#------------------------------#
UninstallServer() {
echo -n "${txtylw}Looking for Minecraft Server"
Dots
if [ -e /home/$(whoami)/Minecraft_Server/bin/minecraft_server.jar ]
then
	echo "${txtgrn}Minecraft Server found!"
	echo "Do you wish to save your settings and save data? [${txtgrn}y/N$txtred]"
	read input
	case $input in
		y | Y ) UninstallServerA
		echo "";;
		n | N ) UninstallServerB
		echo "";;
		* ) echo "Invalid choice!";;
	esac
UninstallServer2
else
	echo "Minecraft Server not detected!$txtrst"
fi
} ## END UninstallServer

#-------------------------------#
#  Uninstall Minecraft Server2  #
#-------------------------------#
UninstallServer2() {
	echo -n "${txtred}Removing Desktop launcher"
	Dots
	rm -rf /home/$(whoami)/Desktop/Minecraft.desktop
	echo ""
#--------------------------------------------
echo -n "Removing menu launcher"
Dots
xdg-desktop-menu uninstall Minecraft_Server.desktop
echo ""
#--------------------------------------------
echo "Uninstalling the icon"
xdg-desktop-icon uninstall Minecraft_Server.png
echo ""
#--------------------------------------------
if [ -e 'home/$(whoami)/Desktop/Minecraft_Server.desktop' ]
then
	echo -n "Removing desktop launcher"
	Dots
	rm -rf '/home/$(whoami)/Desktop/Minecraft_Server.desktop'
	echo ""
fi
#--------------------------------------------
if [ -e /usr/local/games/minecraft_server ]
then
	echo -n "Removing shell launcher in '/usr/local/games'"
	Dots
	echo "${txtylw}That requires root access"
	sudo rm -rf /usr/local/games/minecraft_server
	echo "${txtgrn}Done!"
	echo ""
fi
#--------------------------------------------
if [ -e /usr/local/bin/minecraft_server ]
then
	echo -n "Removing shell launcher in '/usr/local/bin'"
	Dots
	echo "That requires root access"
	sudo rm -rf /usr/local/bin/minecraft_server
	echo "${txtgrn}Done!"
	echo ""
fi
echo "${txtred}Minecraft Server has been uninstalled$txtrst"
} ## END UninstallServer2

#-------------------------------#
#  Uninstall Minecraft ServerA  #
#-------------------------------#
UninstallServerA() {
	echo -n "${txtylw}Uninstalling while keeping some items in ~/Minecraft_Server/"
	Dots
	echo ""
if [ -d /home/$(whoami)/Minecraft_Server/bin ]
then
	echo -n "${txtred}Removing Minecraft Sever bin folder"
	Dots
	rm -rf /home/$(whoami)/Minecraft_Server/bin
echo ""; echo "${txtgrn}Done!$txtrst"; echo""
fi
} ## END UninstallServerA

#-------------------------------#
#  Uninstall Minecraft ServerB  #
#-------------------------------#
UninstallServerB() {
echo -n "${txtred}Removing the Minecraft Server folder"
Dots
rm -rf /home/$(whoami)/Minecraft_Server
echo ""; echo "${txtgrn}Done!$txtrst"; echo""
} ## END UninstallServerB

#-------------------#
#  Troubleshooting  #
#-------------------#
Troubleshoot() {
echo "------------------------------------------------------"
echo ""
echo "$txtbld${txtgrn}#------------------------#"
echo "#  Troubleshooting Menu  #"
echo "#------------------------#$txtrst"

echo "${txtgrn}What would you like to do?"; echo ""
echo "0) Check to see default Java client (Recommended)"
echo "1) Install/update Java"
echo "2) Update Lightweight Java Game Library"
echo "3) Use Sun Java 6 to run minecraft from now on(May not work)"
echo "4) Use Oracle Java 7 to run minecraft from now on"
echo "5) Use OpenJDK 7 to run minecraft from now on"
echo "6) Manually select which Java to use"
echo "7) These options didn't solve my problem!"
echo "8) Return to the main menu"
read input -p "${txtbld}Enter your choice [1-8]$txtrst"
case $input in
	0 ) java -version
	javac -version;;
	1 ) JavaMenu;;
	2 ) UpdateLwjgl
	Troubleshoot;;
	3 )SunJavaDefault
	Troubleshoot;;
	4 )OracleJavaDefaultA
	Troubleshoot;;
	5 ) OpenJDKDefault
	Troubleshoot;;
	6 ) sudo update-alternatives --config java
	sudo update-alternatives --config javac
	sudo update-alternatives --config javaws
	echo ""; echo "Done!"; echo "";;
	7 ) echo "-------------------------------------------------"
	echo "${txtylw}If these Troubleshooting options didn't fix your, problem, I'd be glad to help you out!"
	echo "Visit the forum at ${txtcyn}http://www.minecraftforum.net/topic/1114574-bash-minecraft-installer/$txtylw or e-mail me at ${txtcyn}enkouyami@mail.com"
	echo "-------------------------------------------------"
	return;;
	8 ) return;;
	* ) echo "${txtred}Invalid choice!$txtrst"
	Troubleshoot
esac
} ## END Troubleshoot

#-----------------------------------------#
#  Update Lightweight Java Game Library   #
#-----------------------------------------#
UpdateLwjgl() {
echo -n "${txtylw}Checking for pre-existing lwjgl.zip"
Dots
echo ""
if [ ! -e /home/$(whoami)/.minecraft/lwjgl/ ]
then
	echo "${txtgrn}Creating '~/.minecraft/lwjgl' folder"
	mkdir /home/$(whoami)/.minecraft/lwjgl
fi
cd /home/$(whoami)/.minecraft/lwjgl
if [ -e /home/$(whoami)/.minecraft/lwjgl/lwjgl.zip ]
then
	echo "lwjgl.zip detected! What would you like to do?"; echo ""
	echo "${txtblu}1) Re-download lwjgl and replace the previous one."
	echo "2) Continue"
	read input -p "${txtbld}Enter your choice [1-2]"
	case $input in
		1 ) echo -n "${txtred}Removing previous lwjgl.zip"
		Dots
		rm /home/$(whoami)/.minecraft/lwjgl/lwjgl.zip
		echo -n "${txtgrn}Downloading"
		Dots
		wget -c http://sourceforge.net/projects/java-game-lib/files/latest/download?source=files
		mv download?source=files lwjgl.zip;;
		2 ) return;;
		* ) echo "${txtred}Invalid choice!$txtrst"
		UpdateLwjgl
	esac
fi
#--------------------------------------------
echo -n "${txtgrn}Extracting archive"
Dots
unzip /home/$(whoami)/.minecraft/lwjgl/lwjgl.zip
#--------------------------------------------
# These files in .minecraft/bin/ will be replaced:
# jinput.jar
# lwjgl.jar
# lwjgl_util.jar
#
# These files in ~/.minecraft/bin/natives/ will be replaced: 
# libjinput-linux.so
# libjinput-linux64.so
# liblwjgl.so
# liblwjgl64.so
# libopenal.so
# libopenal64.so
echo -n "${txtgrn}Updating local lwjgl files"
Dots
echo ""
cd /home/$(whoami)/.minecraft/lwjgl/lwjgl-2.8.3/jar/
mv jinput.jar /home/$(whoami)/.minecraft/bin/
mv lwjgl.jar /home/$(whoami)/.minecraft/bin/
mv lwjgl_util.jar /home/$(whoami)/.minecraft/bin/
cd /home/$(whoami)/.minecraft/lwjgl/lwjgl-2.8.3/native/linux
mv libjinput-linux.so /home/$(whoami)/.minecraft/bin/natives
mv libjinput-linux64.so /home/$(whoami)/.minecraft/bin/natives
mv liblwjgl.so /home/$(whoami)/.minecraft/bin/natives
mv liblwjgl64.so /home/$(whoami)/.minecraft/bin/natives
mv libopenal.so /home/$(whoami)/.minecraft/bin/natives
mv libopenal64.so /home/$(whoami)/.minecraft/bin/natives
rm -rf /home/$(whoami)/.minecraft/lwjgl/lwjgl-2.8.3/
echo ""; echo "${txtgrn}Done!$txtrst"; echo ""
} ## END UpdateLwjgl

#--------#
#  Main  #
#--------#
Main() {
echo "------------------------------------------------------"
echo ""
echo "What would you like to do?"; echo ""
echo "${txtgrn}1) Check installed Java versions"
echo "2) Java Menu"
echo "3) Install Minecraft"
echo "4) Uninstall Minecraft"
echo "5) Install Minecraft Server"
echo "6) Uninstall Minecraft Server"
echo "7) Troubleshooting"
echo "8) Show license"
echo "9) Exit"
if [ -e /usr/local/games/minecraft ] && [ -e /home/$(whoami)/.minecraft/minecraft.jar ]
then
echo "0) Play Minecraft!"
fi
if [ -e /usr/local/games/minecraft_server ] && [ -e /home/$(whoami)/Minecraft_Server/bin/minecraft_server.jar ]
then
echo "-) Start Minecraft Server!"
fi
echo "$txtrst"
while [ input != 1 ] && [ input != 2 ] && [ input != 3 ] && [ input != 4 ] && [ input != 5 ] && [ input != 6 ] && [ input != 7 ] && [ input != 8 ] && [ input != 9 ]; do

read -p "$txtbld Enter your choice [0-9,-,*]$txtrst" input
case $input in
	1 ) CheckJavas
	Main
	return;;
	2 ) JavaMenu
	Main
	return
	;;
	3 ) InstallMinecraft
	Main
	return;;
	4 ) UninstallMinecraft
	Main
	return;;
	5 ) ServerInstall
	Main
	return;;
	6 ) UninstallServer
	Main
	return;;
	7 ) Troubleshoot
	Main
	return;;
	'show w'|'show c' ) licenseMenu
	Main
	return;;
	9 | q ) exit;;
	0 ) if [ -e /usr/local/games/minecraft ] && [ -e /home/$(whoami)/.minecraft/minecraft.jar ]
then
			minecraft
		fi;;
	- ) if [ -e /usr/local/games/minecraft_server ] && [ -e /home/$(whoami)/Minecraft_Server/minecraft_server.jar ]
then
			minecraft_server
		fi;;
	* ) echo "${txtred}Invalid choice!$txtrst"
	Main
esac
done
} ## END Main

#-------------------------#
#      Call The Main      #
#-------------------------#
Main
# THE END
